// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Spicejet.com.BookingPageClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class BookingPage
    {
        
        #region Properties
        public CheapAirTicketsOnlinWindow CheapAirTicketsOnlinWindow
        {
            get
            {
                if ((this.mCheapAirTicketsOnlinWindow == null))
                {
                    this.mCheapAirTicketsOnlinWindow = new CheapAirTicketsOnlinWindow();
                }
                return this.mCheapAirTicketsOnlinWindow;
            }
        }
        
        public SpiceJetFlightBookinWindow SpiceJetFlightBookinWindow
        {
            get
            {
                if ((this.mSpiceJetFlightBookinWindow == null))
                {
                    this.mSpiceJetFlightBookinWindow = new SpiceJetFlightBookinWindow();
                }
                return this.mSpiceJetFlightBookinWindow;
            }
        }
        #endregion
        
        #region Fields
        private CheapAirTicketsOnlinWindow mCheapAirTicketsOnlinWindow;
        
        private SpiceJetFlightBookinWindow mSpiceJetFlightBookinWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class CheapAirTicketsOnlinWindow : BrowserWindow
    {
        
        public CheapAirTicketsOnlinWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Cheap Air Tickets Online, International Flights to India, Cheap International Fli" +
                "ght Deals | Sp";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Cheap Air Tickets Online, International Flights to India, Cheap International Fli" +
                    "ght Deals | Sp");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public CheapAirTicketsOnlinDocument CheapAirTicketsOnlinDocument
        {
            get
            {
                if ((this.mCheapAirTicketsOnlinDocument == null))
                {
                    this.mCheapAirTicketsOnlinDocument = new CheapAirTicketsOnlinDocument(this);
                }
                return this.mCheapAirTicketsOnlinDocument;
            }
        }
        #endregion
        
        #region Fields
        private CheapAirTicketsOnlinDocument mCheapAirTicketsOnlinDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class CheapAirTicketsOnlinDocument : HtmlDocument
    {
        
        public CheapAirTicketsOnlinDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Cheap Air Tickets Online, International Flights to India, Cheap International Fli" +
                "ght Deals | SpiceJet Airlines";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Select.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://book.spicejet.com/Select.aspx";
            this.WindowTitles.Add("Cheap Air Tickets Online, International Flights to India, Cheap International Fli" +
                    "ght Deals | Sp");
            #endregion
        }
        
        #region Properties
        public WrapperPane WrapperPane
        {
            get
            {
                if ((this.mWrapperPane == null))
                {
                    this.mWrapperPane = new WrapperPane(this);
                }
                return this.mWrapperPane;
            }
        }
        #endregion
        
        #region Fields
        private WrapperPane mWrapperPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class WrapperPane : HtmlDiv
    {
        
        public WrapperPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "wrapper";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Modify Search\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nRound Trip\r";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"wrapper\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "19";
            this.WindowTitles.Add("Cheap Air Tickets Online, International Flights to India, Cheap International Fli" +
                    "ght Deals | Sp");
            #endregion
        }
        
        #region Properties
        public HtmlDiv ItemPane
        {
            get
            {
                if ((this.mItemPane == null))
                {
                    this.mItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "step2 hide-mobile";
                    this.mItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"step2 hide-mobile\"";
                    this.mItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "56";
                    this.mItemPane.WindowTitles.Add("Cheap Air Tickets Online, International Flights to India, Cheap International Fli" +
                            "ght Deals | Sp");
                    #endregion
                }
                return this.mItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SpiceJetFlightBookinWindow : BrowserWindow
    {
        
        public SpiceJetFlightBookinWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public SpiceJetFlightBookinDocument SpiceJetFlightBookinDocument
        {
            get
            {
                if ((this.mSpiceJetFlightBookinDocument == null))
                {
                    this.mSpiceJetFlightBookinDocument = new SpiceJetFlightBookinDocument(this);
                }
                return this.mSpiceJetFlightBookinDocument;
            }
        }
        #endregion
        
        #region Fields
        private SpiceJetFlightBookinDocument mSpiceJetFlightBookinDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SpiceJetFlightBookinDocument : HtmlDocument
    {
        
        public SpiceJetFlightBookinDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://spicejet.com/";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox AdultComboBox
        {
            get
            {
                if ((this.mAdultComboBox == null))
                {
                    this.mAdultComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mAdultComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ctl00_mainContent_ddl_Adult";
                    this.mAdultComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ctl00$mainContent$ddl_Adult";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "9";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "wMed1s required";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ctl00$mainContent$ddl_Adult\" class";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "3";
                    this.mAdultComboBox.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mAdultComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mAdultComboBox;
        #endregion
    }
}
