// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Spicejet.com.HomepageClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class Homepage
    {
        
        /// <summary>
        /// VerifyBrowserLaunchSuccess - Use 'VerifyBrowserLaunchSuccessExpectedValues' to pass parameters into this method.
        /// </summary>
        public void VerifyBrowserLaunchSuccess()
        {
            #region Variable Declarations
            HtmlHyperlink spiceJetHyperlink = this.SpiceJetFlightBookinWindow.SpiceJetFlightBookinDocument.HeaderPane.SpiceJetHyperlink;
            #endregion

            // Verify that the 'TagName' property of 'SpiceJet' link equals 'A'
            Assert.AreEqual(this.VerifyBrowserLaunchSuccessExpectedValues.SpiceJetHyperlinkTagName, spiceJetHyperlink.TagName, "Url is opening");
        }
        
        #region Properties
        public virtual VerifyBrowserLaunchSuccessExpectedValues VerifyBrowserLaunchSuccessExpectedValues
        {
            get
            {
                if ((this.mVerifyBrowserLaunchSuccessExpectedValues == null))
                {
                    this.mVerifyBrowserLaunchSuccessExpectedValues = new VerifyBrowserLaunchSuccessExpectedValues();
                }
                return this.mVerifyBrowserLaunchSuccessExpectedValues;
            }
        }
        
        public SpiceJetFlightBookinWindow SpiceJetFlightBookinWindow
        {
            get
            {
                if ((this.mSpiceJetFlightBookinWindow == null))
                {
                    this.mSpiceJetFlightBookinWindow = new SpiceJetFlightBookinWindow();
                }
                return this.mSpiceJetFlightBookinWindow;
            }
        }
        #endregion
        
        #region Fields
        private VerifyBrowserLaunchSuccessExpectedValues mVerifyBrowserLaunchSuccessExpectedValues;
        
        private SpiceJetFlightBookinWindow mSpiceJetFlightBookinWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'VerifyBrowserLaunchSuccess'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class VerifyBrowserLaunchSuccessExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'TagName' property of 'SpiceJet' link equals 'A'
        /// </summary>
        public string SpiceJetHyperlinkTagName = "A";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SpiceJetFlightBookinWindow : BrowserWindow
    {
        
        public SpiceJetFlightBookinWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public SpiceJetFlightBookinDocument SpiceJetFlightBookinDocument
        {
            get
            {
                if ((this.mSpiceJetFlightBookinDocument == null))
                {
                    this.mSpiceJetFlightBookinDocument = new SpiceJetFlightBookinDocument(this);
                }
                return this.mSpiceJetFlightBookinDocument;
            }
        }
        
        public UISpiceJetFlightBookinDocument UISpiceJetFlightBookinDocument
        {
            get
            {
                if ((this.mUISpiceJetFlightBookinDocument == null))
                {
                    this.mUISpiceJetFlightBookinDocument = new UISpiceJetFlightBookinDocument(this);
                }
                return this.mUISpiceJetFlightBookinDocument;
            }
        }
        #endregion
        
        #region Fields
        private SpiceJetFlightBookinDocument mSpiceJetFlightBookinDocument;
        
        private UISpiceJetFlightBookinDocument mUISpiceJetFlightBookinDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SpiceJetFlightBookinDocument : HtmlDocument
    {
        
        public SpiceJetFlightBookinDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://spicejet.com/";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HeaderPane HeaderPane
        {
            get
            {
                if ((this.mHeaderPane == null))
                {
                    this.mHeaderPane = new HeaderPane(this);
                }
                return this.mHeaderPane;
            }
        }
        
        public Smoothmenu1Pane Smoothmenu1Pane
        {
            get
            {
                if ((this.mSmoothmenu1Pane == null))
                {
                    this.mSmoothmenu1Pane = new Smoothmenu1Pane(this);
                }
                return this.mSmoothmenu1Pane;
            }
        }
        
        public Ctl00_mainContent_rbTable Ctl00_mainContent_rbTable
        {
            get
            {
                if ((this.mCtl00_mainContent_rbTable == null))
                {
                    this.mCtl00_mainContent_rbTable = new Ctl00_mainContent_rbTable(this);
                }
                return this.mCtl00_mainContent_rbTable;
            }
        }
        
        public HtmlEdit CTXTEdit
        {
            get
            {
                if ((this.mCTXTEdit == null))
                {
                    this.mCTXTEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mCTXTEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_mainContent_ddl_originStation1_CTXT";
                    this.mCTXTEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00_mainContent_ddl_originStation1_CTXT";
                    this.mCTXTEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mCTXTEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mCTXTEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mCTXTEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "select_CTXT";
                    this.mCTXTEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00_mainContent_ddl_originStatio";
                    this.mCTXTEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "12";
                    this.mCTXTEdit.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mCTXTEdit;
            }
        }
        
        public HtmlEdit CTXTEdit2
        {
            get
            {
                if ((this.mCTXTEdit2 == null))
                {
                    this.mCTXTEdit2 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mCTXTEdit2.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_mainContent_ddl_destinationStation1_CTXT";
                    this.mCTXTEdit2.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00_mainContent_ddl_destinationStation1_CTXT";
                    this.mCTXTEdit2.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mCTXTEdit2.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mCTXTEdit2.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mCTXTEdit2.FilterProperties[HtmlEdit.PropertyNames.Class] = "select_CTXT";
                    this.mCTXTEdit2.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00_mainContent_ddl_destinationS";
                    this.mCTXTEdit2.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "14";
                    this.mCTXTEdit2.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mCTXTEdit2;
            }
        }
        
        public DropdownGroup1Pane DropdownGroup1Pane
        {
            get
            {
                if ((this.mDropdownGroup1Pane == null))
                {
                    this.mDropdownGroup1Pane = new DropdownGroup1Pane(this);
                }
                return this.mDropdownGroup1Pane;
            }
        }
        
        public DropdownGroup1Pane2 DropdownGroup1Pane2
        {
            get
            {
                if ((this.mDropdownGroup1Pane2 == null))
                {
                    this.mDropdownGroup1Pane2 = new DropdownGroup1Pane2(this);
                }
                return this.mDropdownGroup1Pane2;
            }
        }
        
        public HtmlEdit FromdateEdit
        {
            get
            {
                if ((this.mFromdateEdit == null))
                {
                    this.mFromdateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mFromdateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_mainContent_txt_Fromdate";
                    this.mFromdateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$mainContent$txt_Fromdate";
                    this.mFromdateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mFromdateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mFromdateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mFromdateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "custom_date_pic required picker-first home-date-pick hasDatepicker valid";
                    this.mFromdateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$mainContent$txt_Fromdate\" cl";
                    this.mFromdateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "16";
                    this.mFromdateEdit.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mFromdateEdit;
            }
        }
        
        public HtmlEdit TodateEdit
        {
            get
            {
                if ((this.mTodateEdit == null))
                {
                    this.mTodateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mTodateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_mainContent_txt_Todate";
                    this.mTodateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$mainContent$txt_Todate";
                    this.mTodateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mTodateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mTodateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mTodateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "custom_date_pic required home-date-pick hasDatepicker";
                    this.mTodateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ctl00$mainContent$txt_Todate\" clas";
                    this.mTodateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "17";
                    this.mTodateEdit.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mTodateEdit;
            }
        }
        
        public UidatepickerdivPane UidatepickerdivPane
        {
            get
            {
                if ((this.mUidatepickerdivPane == null))
                {
                    this.mUidatepickerdivPane = new UidatepickerdivPane(this);
                }
                return this.mUidatepickerdivPane;
            }
        }
        
        public HtmlInputButton FindFlightsButton
        {
            get
            {
                if ((this.mFindFlightsButton == null))
                {
                    this.mFindFlightsButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mFindFlightsButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_mainContent_btn_FindFlights";
                    this.mFindFlightsButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$mainContent$btn_FindFlights";
                    this.mFindFlightsButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Find Flights";
                    this.mFindFlightsButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mFindFlightsButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mFindFlightsButton.FilterProperties[HtmlButton.PropertyNames.Class] = "buttonN";
                    this.mFindFlightsButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "name=\"ctl00$mainContent$btn_FindFlights\"";
                    this.mFindFlightsButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "22";
                    this.mFindFlightsButton.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mFindFlightsButton;
            }
        }
        
        public HtmlComboBox AdultComboBox
        {
            get
            {
                if ((this.mAdultComboBox == null))
                {
                    this.mAdultComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mAdultComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ctl00_mainContent_ddl_Adult";
                    this.mAdultComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ctl00$mainContent$ddl_Adult";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "9";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "wMed1s required";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ctl00$mainContent$ddl_Adult\" class";
                    this.mAdultComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "3";
                    this.mAdultComboBox.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mAdultComboBox;
            }
        }
        #endregion
        
        #region Fields
        private HeaderPane mHeaderPane;
        
        private Smoothmenu1Pane mSmoothmenu1Pane;
        
        private Ctl00_mainContent_rbTable mCtl00_mainContent_rbTable;
        
        private HtmlEdit mCTXTEdit;
        
        private HtmlEdit mCTXTEdit2;
        
        private DropdownGroup1Pane mDropdownGroup1Pane;
        
        private DropdownGroup1Pane2 mDropdownGroup1Pane2;
        
        private HtmlEdit mFromdateEdit;
        
        private HtmlEdit mTodateEdit;
        
        private UidatepickerdivPane mUidatepickerdivPane;
        
        private HtmlInputButton mFindFlightsButton;
        
        private HtmlComboBox mAdultComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class HeaderPane : HtmlDiv
    {
        
        public HeaderPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "header";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Reservations (24/7) \r\n\r\n+91 987 180 3333";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"header\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink SpiceJetHyperlink
        {
            get
            {
                if ((this.mSpiceJetHyperlink == null))
                {
                    this.mSpiceJetHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mSpiceJetHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mSpiceJetHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mSpiceJetHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mSpiceJetHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = null;
                    this.mSpiceJetHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Default.aspx";
                    this.mSpiceJetHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "SpiceJet";
                    this.mSpiceJetHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://spicejet.com/Default.aspx";
                    this.mSpiceJetHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "spicejet_logo";
                    this.mSpiceJetHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"SpiceJet\" class=\"spicejet_logo\" h";
                    this.mSpiceJetHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mSpiceJetHyperlink.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mSpiceJetHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mSpiceJetHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class Smoothmenu1Pane : HtmlDiv
    {
        
        public Smoothmenu1Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "smoothmenu1";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "About Us   \r\n\r\nCorporate Overview \r\n\r\n\r\n";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ddsmoothmenu";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ddsmoothmenu\" id=\"smoothmenu1\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink AboutUsHyperlink
        {
            get
            {
                if ((this.mAboutUsHyperlink == null))
                {
                    this.mAboutUsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mAboutUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mAboutUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mAboutUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mAboutUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "About Us   ";
                    this.mAboutUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "void(0);";
                    this.mAboutUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mAboutUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:void(0);";
                    this.mAboutUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mAboutUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"javascript:void(0);\"";
                    this.mAboutUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mAboutUsHyperlink.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mAboutUsHyperlink;
            }
        }
        
        public HtmlHyperlink ContactUsHyperlink
        {
            get
            {
                if ((this.mContactUsHyperlink == null))
                {
                    this.mContactUsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mContactUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mContactUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mContactUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mContactUsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Contact Us   ";
                    this.mContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "void(0);";
                    this.mContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = "Contact Us";
                    this.mContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:void(0);";
                    this.mContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "title=\"Contact Us\" href=\"javascript:void";
                    this.mContactUsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "8";
                    this.mContactUsHyperlink.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mContactUsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mAboutUsHyperlink;
        
        private HtmlHyperlink mContactUsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class Ctl00_mainContent_rbTable : HtmlTable
    {
        
        public Ctl00_mainContent_rbTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = "ctl00_mainContent_rbtnl_Trip";
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Round Trip\r\n\r\nOne Way";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"tblTrip\" id=\"ctl00_mainContent_rbtnl_Trip\" border=\"0\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "tblTrip";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "3";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HtmlLabel RoundTripLabel
        {
            get
            {
                if ((this.mRoundTripLabel == null))
                {
                    this.mRoundTripLabel = new HtmlLabel(this);
                    #region Search Criteria
                    this.mRoundTripLabel.SearchProperties[HtmlLabel.PropertyNames.Id] = null;
                    this.mRoundTripLabel.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
                    this.mRoundTripLabel.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "ctl00_mainContent_rbtnl_Trip_0";
                    this.mRoundTripLabel.SearchProperties[HtmlLabel.PropertyNames.InnerText] = "Round Trip";
                    this.mRoundTripLabel.FilterProperties[HtmlLabel.PropertyNames.Class] = null;
                    this.mRoundTripLabel.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "for=\"ctl00_mainContent_rbtnl_Trip_0\"";
                    this.mRoundTripLabel.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "1";
                    this.mRoundTripLabel.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mRoundTripLabel;
            }
        }
        
        public HtmlLabel OneWayLabel
        {
            get
            {
                if ((this.mOneWayLabel == null))
                {
                    this.mOneWayLabel = new HtmlLabel(this);
                    #region Search Criteria
                    this.mOneWayLabel.SearchProperties[HtmlLabel.PropertyNames.Id] = null;
                    this.mOneWayLabel.SearchProperties[HtmlLabel.PropertyNames.Name] = null;
                    this.mOneWayLabel.SearchProperties[HtmlLabel.PropertyNames.LabelFor] = "ctl00_mainContent_rbtnl_Trip_1";
                    this.mOneWayLabel.SearchProperties[HtmlLabel.PropertyNames.InnerText] = "One Way";
                    this.mOneWayLabel.FilterProperties[HtmlLabel.PropertyNames.Class] = null;
                    this.mOneWayLabel.FilterProperties[HtmlLabel.PropertyNames.ControlDefinition] = "for=\"ctl00_mainContent_rbtnl_Trip_1\"";
                    this.mOneWayLabel.FilterProperties[HtmlLabel.PropertyNames.TagInstance] = "2";
                    this.mOneWayLabel.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mOneWayLabel;
            }
        }
        #endregion
        
        #region Fields
        private HtmlLabel mRoundTripLabel;
        
        private HtmlLabel mOneWayLabel;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class DropdownGroup1Pane : HtmlDiv
    {
        
        public DropdownGroup1Pane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "dropdownGroup1";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "India\r\n\r\n\r\nAgartala (IXA)\r\n\r\n\r\nAhmedabad";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"dropdownGroup1\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "38";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink GoaGOIHyperlink
        {
            get
            {
                if ((this.mGoaGOIHyperlink == null))
                {
                    this.mGoaGOIHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mGoaGOIHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mGoaGOIHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mGoaGOIHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mGoaGOIHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Goa (GOI)";
                    this.mGoaGOIHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mGoaGOIHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mGoaGOIHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://spicejet.com/#";
                    this.mGoaGOIHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mGoaGOIHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "onclick=\"javascript:$CityDropDown.SetSel";
                    this.mGoaGOIHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "13";
                    this.mGoaGOIHyperlink.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mGoaGOIHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mGoaGOIHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class DropdownGroup1Pane2 : HtmlDiv
    {
        
        public DropdownGroup1Pane2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "dropdownGroup1";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "India\r\n\r\n\r\nAhmedabad (AMD)\r\n\r\n\r\nAmritsar";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"dropdownGroup1\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "48";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink MumbaiBOMHyperlink
        {
            get
            {
                if ((this.mMumbaiBOMHyperlink == null))
                {
                    this.mMumbaiBOMHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mMumbaiBOMHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mMumbaiBOMHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mMumbaiBOMHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mMumbaiBOMHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Mumbai (BOM)";
                    this.mMumbaiBOMHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mMumbaiBOMHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mMumbaiBOMHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://spicejet.com/#";
                    this.mMumbaiBOMHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mMumbaiBOMHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "onclick=\"javascript:$CityDropDown.SetSel";
                    this.mMumbaiBOMHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "18";
                    this.mMumbaiBOMHyperlink.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mMumbaiBOMHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mMumbaiBOMHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UidatepickerdivPane : HtmlDiv
    {
        
        public UidatepickerdivPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ui-datepicker-div";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Prev\r\n\r\nNovember 2015\r\n\r\n\r\nSu\r\n\r\nMo\r\n\r\nT";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all ui-dat" +
                "epicker-multi ui-datepicker-multi-2";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" +
                " ui-datepicker-multi ui-datepicker-multi-2\" id=\"ui-datepicker-div\" style=\"left: " +
                "419.44px; top: 277px; width: 34em; display: block; position: absolute; z-index: " +
                "14;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "466";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink Item31Hyperlink
        {
            get
            {
                if ((this.mItem31Hyperlink == null))
                {
                    this.mItem31Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mItem31Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mItem31Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mItem31Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mItem31Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "31";
                    this.mItem31Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mItem31Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mItem31Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://spicejet.com/#";
                    this.mItem31Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ui-state-default";
                    this.mItem31Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ui-state-default\" href=\"#\"";
                    this.mItem31Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "34";
                    this.mItem31Hyperlink.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mItem31Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mItem31Hyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISpiceJetFlightBookinDocument : HtmlDocument
    {
        
        public UISpiceJetFlightBookinDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.spicejet.com/";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public UidatepickerdivPane1 UidatepickerdivPane
        {
            get
            {
                if ((this.mUidatepickerdivPane == null))
                {
                    this.mUidatepickerdivPane = new UidatepickerdivPane1(this);
                }
                return this.mUidatepickerdivPane;
            }
        }
        #endregion
        
        #region Fields
        private UidatepickerdivPane1 mUidatepickerdivPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UidatepickerdivPane1 : HtmlDiv
    {
        
        public UidatepickerdivPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ui-datepicker-div";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Prev\r\n\r\nNovember 2015\r\n\r\n\r\nSu\r\n\r\nMo\r\n\r\nT";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all ui-dat" +
                "epicker-multi ui-datepicker-multi-2";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" +
                " ui-datepicker-multi ui-datepicker-multi-2\" id=\"ui-datepicker-div\" style=\"left: " +
                "419.44px; top: 277px; width: 34em; display: block; position: absolute; z-index: " +
                "14;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "448";
            this.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink Item30Hyperlink
        {
            get
            {
                if ((this.mItem30Hyperlink == null))
                {
                    this.mItem30Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mItem30Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mItem30Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mItem30Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mItem30Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "30";
                    this.mItem30Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mItem30Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mItem30Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://www.spicejet.com/#";
                    this.mItem30Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ui-state-default";
                    this.mItem30Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ui-state-default\" href=\"#\"";
                    this.mItem30Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "14";
                    this.mItem30Hyperlink.WindowTitles.Add("SpiceJet - Flight Booking for Domestic and International, Cheap Air Tickets");
                    #endregion
                }
                return this.mItem30Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mItem30Hyperlink;
        #endregion
    }
}
